### ISSUE TITLE
Ordered field has no validation function

### ISSUE THREAD

**Issue by tcouch** [tcouch/pandas-data-dictionary#8]
The ordered field is included in the list of validation columns, but has no validation function as it doesn't need one.
Steps to reproduce:
```
>>> df.dd.set_categories('rating',category_list=['1','2','3','4','5'],ordered=True)
>>> df.dd.validate('rating')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\cceatco\Documents\Development\pandas-data-dictionary\pandas_data_dictionary\pd_dd.py", line 143, in validate
    valid_series = getattr(self,'validate_' + parameter)(var,value)
AttributeError: 'DataDictionaryAccessor' object has no attribute 'validate_ordered'
```

**Comment by tcouch** [comment]
Options:
1. Create a validate_ordered function and get it to return True whatever.
2. Remove ordered from the validation_params dict in dd.validate()
